    var default_changes = {
  "only":"just",
"fair shake":"justice",
"grounds":"justification",
"wellgrounded":"justified",
"uphold":"justify",
"youngster":"juvenile",
"daredevil":"kamikaze",
"boomer":"kangaroo",
"silk-treewool":"kapok",
"singalong":"karaoke",
"doings":"karma",
"mansboat":"kayak",
"doghouse":"kennel",
"loveappledip":"ketchup",
"brimoven":"kilnin",
"lovespark":"kilig",
"childeryard":"kindergarten",
"thousandbit":"kilogram",
"thousandbits":"kilograms",
"thousandmeter":"kilometer",
"thousandmeters":"kilometers",
"booth":"kiosk",
"mad theft":"kleptomania",
"mad thief":"kleptomaniac",
"knowledgeful":"knowledgeable",
"Mornfrithland":"Korea",
"bootlick":"kowtow",
"silk-treewool tree":"kapok tree",
"hiddenmote":"krypton",
"landdelf":"landmine",
"work":"labor",
"worker":"laborer",
"workshop":"laboratory",
"backbreaking":"laborious",
"maze":"labyrinth",
"cut":"lacerate",
"sad":"lachrymose",
"lackadaisy":"lackadaisical",
"dim":"lacklustre",
"tearbone":"lacrimal bone",
"milksweet":"lactose",
"dearth":"lacuna",
"sealock":"lagoon",
"berate":"lambaste",
"mourn":"lament",
"bemoaning":"lamentable",
"beacon":"lamp",
"lightvat":"lampion",
"ord network":"lan",
"tongue":"language",
"limp":"languid",
"pine":"languish",
"listlessness":"languor",
"woolwax":"lanolin",
"ingraver":"lapidary",
"fluff":"lapse",
"great":"large",
"broadly":"largely",
"stevenbox":"larynx",
"foul":"lascivious",
"losyr":"laser",
"losyrs":"lasers",
"throwsling":"lasso",
"bowheight":"latitude",
"bowheight":"latitudes",
"herry":"laud",
"laughworthy":"laughable",
"take off":"launch",
"wash":"launder",
"washhouse":"laundrette",
"wash":"laundry",
"molten rock":"lava",
"mead":"lawn",
"lawman":"lawyer",
"careless":"lax",
"stoolloosener":"laxative",
"yedding":"lay",
"newbie":"layman",
"flatscreen":"lcd",
"leak":"leakage",
"waystound":"league",
"let":"lease",
"lead":"leash",
"hot":"lecherous",
"forereading":"lecture",
"forereader":"lecturer",
"leatherhosen":"lederhosen",
"bequest":"legacy",
"lawful":"legal",
"make lawful":"legalize",
"made lawful":"legalized",
"making lawful":"legalizing",
"making lawful":"legalization",
"make lawful":"legalise",
"made lawful":"legalised",
"making lawful":"legalising",
"making lawful":"legalisation",
"key":"legend",
"talewoven":"legendary",
"readsome":"legible",
"law":"legislation",
"lawmaker":"legislator",
"lawmaking body":"legislature",
"rightful":"legitimate",
"ovest":"legume",
"blackdriff":"leishmaniasis",
"free":"leisure",
"rest":"leisure have",
"sourapple":"lemon",
"soothing":"lenitive",
"eyeglass":"lens",
"moths":"lepidoptera",
"lightmote":"lepton",
"dyke slang":"lesbian",
"teaching":"lesson",
"ling":"let",
"deadly":"lethal",
"sluggish":"lethargic",
"listlessness":"lethargy",
"bookstaff":"letter",
"sleepwort":"lettuce",
"blood MTF":"leukemia",
"flat":"level",
"switch":"lever",
"heft":"leverage",
"young hare":"leveret",
"nicker":"leviathan",
"wordhoard":"lexicon",
"queer":"lgbt",
"downside":"liability",
"guilty":"liable",
"broadminded":"liberal",
"freewardness":"liberalism",
"freesome":"libertarian",
"freesome":"libertarianism",
"free":"liberate",
"freeing":"liberation",
"freedom":"liberty",
"bookhouse":"library",
"bookman":"librarian",
"leave":"license",
"hot":"licentious",
"lungwort":"lichen",
"helpmate":"lieutenant",
"belt":"ligature",
"elderbloom":"lilac",
"lilie":"lily",
"seabloom":"lily pad",
"netherworld":"limbo",
"crush":"limerence",
"bound":"limit",
"cramp":"limitation",
"seethrough":"limpid",
"bloodties":"lineage",
"streak":"line",
"straightwise":"linear",
"flaxcloth":"linen",
"knickerwear":"lingerie",
"tonguely":"linguistic",
"speechlore":"linguistics",
"speechlorer":"linguist",
"lintwhite":"linnet",
"corksail":"linoleum",
"flaxseed":"linseed",
"lewcat":"lion",
"fat":"lipid",
"flowsome":"liquid",
"mead":"liquor",
"sweetroot":"licorice",
"sweetroot":"liquorice",
"beesong":"litany",
"wordly":"literal",
"word for word":"literally",
"written":"literary",
"dreaddevils":"literary horror",
"learned":"literate",
"bookcraft":"literature",
"stonestuff":"lithium",
"stonewrit":"lithograph",
"stonewritting":"lithography",
"searim":"littoral",
"ledework":"liturgy",
"athex":"lizard",
"sheepolvend":"llama",
"lap":"lobe",
"lapdeal":"lobotomy",
"hummer":"lobster",
"near":"local",
"shire":"locality",
"find":"locate",
"spot":"location",
"draughtwain":"locomotive",
"dwell":"lodge",
"boarder":"lodger",
"splittle":"logarithm",
"witcraft":"logic",
"yieldship":"logistics",
"brandmark":"logo",
"Word":"logos",
"length":"longitude",
"lende":"loin",
"feathertongued":"loquacious",
"widowhunter":"lothario",
"idle":"lounge",
"stalwart":"loyal",
"stalwart":"loyalist",
"troth":"loyalty",
"slick":"lubricate",
"slippery":"lubricated",
"hot":"lubricious",
"shining":"lucid",
"lightbearer":"lucifer",
"lyingnews":"lügenpresse",
"cradlesong":"lullaby",
"lightbearing":"luminous",
"madness":"lunacy",
"moonly":"lunar",
"greater ladylips":"labia majora",
"lesser ladylips":"labia minora",
"workship":"labor union",
"light beer":"lager beer",
"Thodsprack Lists":"language arts",
"skystone":"lapis lazuli",
"lifeswend":"life course",
"intellectual":"life of the mind",
"shared tongue":"lingua franca",
"sheerspeechcraft":"linguistic purism",
"moon shape":"lunar phase",
"moonbone":"lunate bone",
"bats":"lunatic",
"wolven":"lupine",
"lush":"luscious",
"gloss":"luster",
"yellowen":"lutein",
"beyellowenning spur":"luteinizing hormone",
"parisstuff":"lutetium",
"silken":"luxe",
"green":"luxuriant",
"galful":"luxurious",
"gal":"luxury",
"warewolfsickness":"lycanthropy",
"suckedderweet":"lymph",
"lox":"lynx",
"gruesome":"macabre",
"soak":"macerate",
"tool":"machine",
"tidewrit":"magazine",
"spellcraft":"magic",
"wizard":"magician",
"deemer":"magistrate",
"worm":"maggot",
"bitterstuff":"magnesium",
"mickman":"magnate",
"lodestone":"magnet",
"blow up":"magnify",
"weight":"magnitude",
"beaverbloom":"magnolia",
"awe":"magpie",
"cripple":"maim",
"keep up":"maintain",
"upkeeped":"maintained",
"upkeep":"maintenance",
"houserede":"matre dhtel",
"highflown":"majestic",
"highness":"majesty",
"higher":"major",
"most":"majority",
"misfit":"maladjusted",
"sickness":"malady",
"brazen":"malapert",
"nitheloft":"malaria",
"man":"male",
"sinner":"malefactor",
"hatefulness":"malevolence",
"bad":"malevolent",
"misdoing":"malfeasance",
"misbehave":"malfunction",
"cattiness":"malice",
"wicked":"malicious",
"evil":"malign",
"hammer":"malleus",
"misfeed":"malnourish",
"maltsweet":"maltose",
"manhandle":"maltreat",
"badware":"malware",
"milkwight":"mammal",
"breast":"mammary",
"furelp":"mammoth",
"handle":"manage",
"foreman":"manager",
"sea cow":"manatee",
"bid":"mandate",
"jowlbone":"mandible",
"skinroot":"mandrake",
"hueleer ape":"mandrill",
"dawnlandish talestrips":"manga",
"keepstuff":"manganese",
"trough":"manger",
"gawksyekes":"mango",
"shrubmarsh":"mangrove",
"madness":"mania",
"mad":"maniac",
"bald":"manifested",
"bespeak":"manifest",
"sweetling":"manifestation",
"sweetling":"manifesto",
"way":"manner",
"quirks":"mannerisms",
"whitecorn":"manna",
"hall":"mansion",
"tameness":"mansuetude",
"mantlereagh":"manta ray",
"beadbug":"mantis",
"wrap":"mantle",
"handly":"manual",
"by hand":"manually",
"frame":"manufacture",
"dung":"manure",
"handwrit":"manuscript",
"Mao Zedong Thought":"maoism",
"plot":"map",
"shinestone":"marble",
"headway":"march",
"Miremonth":"March",
"weed":"marijuana",
"shipyger":"marine",
"stringdoll":"marionette",
"sealike":"maritime",
"kingswort":"marjoram",
"market":"market",
"athelman":"marquess",
"wedding":"marriage",
"wed":"marry",
"wedded":"married",
"pursedeer":"marsupial",
"bloot":"martyr",
"wonder":"marvel",
"wonderful":"marvelous",
"Marxdom":"Marxism",
"big":"massive",
"hide":"mask",
"achelove":"masochism",
"seeksorrow":"masochist",
"stonecutter":"mason",
"stonecraft":"masonry",
"meshplay":"masque",
"meshtumb":"masquerade",
"bulk":"mass",
"bulk middle":"mass media",
"slaughter":"massacre",
"chew":"masticate",
"alearn":"master",
"breasttooth":"mastodon",
"frig":"masturbate",
"selflove":"masturbation",
"lighter":"match",
"weighty":"material",
"motherly":"maternal",
"rimecraft":"mathematics",
"wedlock":"matrimony",
"womb":"matrix",
"markworth":"matter",
"grown":"mature",
"jawbone":"maxilla",
"uttermost":"maximum",
"Threemilkmonth":"May",
"crippling":"mayhem",
"yolkdip":"mayonnaise",
"boroughreeve":"mayor",
"McCarthydom":"McCarthyism",
"way":"means",
"beat":"measure",
"workcraft":"mechanics",
"middle":"media",
"halfway":"mediate",
"formiddler":"mediator",
"healing":"medicine",
"middle eld":"medieval",
"middling":"mediocre",
"hedge":"meditate",
"inwardness":"meditation",
"evenspan":"medium",
"mashup":"medley",
"mickle":"mega",
"mickletooth":"megalodon",
"mickleborough":"megalopolis",
"bullhorn":"megaphone",
"frumecleaving":"meiosis",
"dreary":"melancholy",
"tussle":"melee",
"gleestaff":"melody",
"rindberry":"melon",
"limb":"member",
"film":"membrane",
"keepsake":"memento",
"mimor":"memory",
"housekeep":"menagerie",
"brimshell":"meningitis",
"monthly":"menstrual",
"monthbleed":"menstruate",
"mindly":"mental",
"mindset":"mentality",
"name":"mention",
"walelist":"menu",
"hireling":"mercenary",
"chapman":"merchant",
"wares":"merchandise",
"delling":"merchandising",
"forgiving":"merciful",
"ruthless":"merciless",
"quicksilver":"mercury",
"kindness":"mercy",
"blend":"merge",
"high noon":"meridian",
"meed":"merit",
"merrywerve":"merrygoround",
"Middle Stone Eld":"mesolithic",
"Mesopotamland":"mesopotamia",
"midmote":"meson",
"earful":"message",
"over":"meta",
"ore":"metal",
"awendshape":"metamorphosis",
"kenning":"metaphor",
"kenningly":"metaphorical",
"falling star":"meteor",
"overloftlore":"meteorology",
"firedamp":"methane",
"way":"method",
"mickleborough":"metropolis",
"Moonsnavel":"Mexico",
"midlife eldth":"mezozoicum",
"small":"micro",
"speckseer":"microscope",
"Midgarth":"Midgard",
"outwander":"migrate",
"hawkish":"militaristic",
"landmightly":"military",
"folkward":"militia",
"yearthousands":"millennia",
"yearthousand":"millennium",
"thousandthbit":"milligram",
"twisandbeat":"millimeter",
"micklered":"million",
"micklereds":"millions",
"hack":"mince",
"ore":"mineral",
"small":"mini",
"lessen":"minimize",
"rede":"minister",
"Ambight":"ministerium",
"ambight":"ministry",
"gleeman":"minstrel",
"youngling":"minor",
"lesserness":"minority",
"min":"minus",
"mazebull":"minotaur",
"mete":"minute",
"flash":"miracle",
"lookingglass":"mirror",
"manhater":"misandrist",
"steal":"misappropriate",
"stealing":"misappropriation",
"misbehaving":"misbehaviour",
"clatter":"miscellanyeous",
"wrongdoing":"misdemeanour",
"tightwad":"miser",
"black":"miserable",
"angst":"misery",
"mishap":"misfortune",
"mishandle":"mismanage",
"womanhater":"misogynist",
"mistroth":"misothesm",
"mislay":"misplace",
"shot":"missile",
"errand":"mission",
"sendling":"missionary",
"soften":"mitigate",
"mightcorn":"mitochondrium",
"brickdealing":"mitosis",
"fistling":"mitten",
"handset":"mobile phone",
"manmade":"mock",
"hoker":"mockery",
"way":"mode",
"build":"model",
"newfangled":"modern",
"benew":"modernise",
"downtoearth":"modest",
"beshedness":"modesty",
"wend":"modify",
"wending":"modification",
"stringbending":"modulation",
"damp":"moist",
"wangtooth":"molar",
"sweetsap":"molasses",
"build":"mold",
"eyeblink":"moment",
"king":"monarch",
"kingdom":"monarchism",
"kingship":"monarchy",
"bedestow":"monastery",
"brotherlife":"monasticism",
"gelt":"money",
"sead":"moneybag",
"watch":"monitor",
"brother":"monk",
"tailape":"monkey",
"lonespeech":"monologue",
"onesell calque":"monopoly",
"onetroth":"monotheism",
"squallrain":"monsoon",
"fiend":"monster",
"Blackhill":"Montenegro",
"keepsake":"monument",
"overwhelming":"monumental",
"heath":"moor",
"greater elk":"moose",
"sidely":"moral",
"uprightness":"morality",
"cheerless":"morbid",
"biting":"mordant",
"deadhouse":"morgue",
"dying":"moribund",
"deadly":"mortal",
"death":"mortality",
"deathen":"mortify",
"wadset":"mortgage",
"lychhouse":"mortuary",
"shardbilth":"mosaic",
"gnat":"mosquito",
"nightflinder":"moth native",
"Lady Lund":"mother nature",
"shrithing":"motion",
"stockstill":"motionless",
"rethe":"motive",
"wheels":"motor",
"watercraft":"motorboat",
"halfwain":"motorcycle",
"highway":"motorway",
"saying":"motto",
"drift":"mound",
"hill":"mount",
"on horseback":"mounted",
"shacklegun":"machine gun",
"bitter earth":"magnesium oxide",
"upkeep":"maitre d'hotel",
"hold":"make sense",
"holds":"makes sense",
"Shrove Tuesday":"mardi gras",
"waterfrith":"marine park",
"wyecrafts":"martial arts",
"my bad":"mea culpa",
"Great Sea":"mediterranean sea",
"Greatyear":"mega annum",
"bedevil":"mental affliction",
"tal rhythm":"meter poetry",
"stealguest":"misappropriative guest",
"tailapepuzzle tree":"monkeypuzzle tree",
"wanderword":"multilanguage word",
"barrow":"mountain",
"barrowy":"mountainous",
"kemp":"moustache",
"shift":"move",
"shift":"movement",
"film":"movie",
"Lord":"mr",
"Lord":"mister",
"Lord":"sir",
"Lady":"mrs",
"slime":"mucus",
"shroud":"muffle",
"felemenning":"multiculturalism",
"many":"multiple",
"manifold":"multiply",
"cluster":"multi",
"allinone":"multipurpose",
"crowd":"multitude",
"linwrapped body":"mummy",
"meanth":"municipality",
"murdery":"murderous",
"brawn":"muscle",
"brawny":"muscular",
"mimmermammer":"muse",
"crafthall":"museum",
"toadstool":"mushroom",
"glee":"music",
"dreamly":"musical",
"gleeman":"musician",
"soonlore":"musicology",
"gun":"musket",
"semp":"mustard",
"gathering":"muster",
"ran":"mussel",
"shapeshift":"mutate",
"dumb":"mute",
"overcripple":"mutilate",
"sheepflesh":"mutton",
"evenway":"mutual",
"net":"mycelium",
"nearsightedness":"myopia",
"wonder":"mystery",
"wondertale":"myth",
"folklore":"mythology",
"depths":"nadir",
"craftless":"naive",
"smart dust":"nanotechnology",
"sleepsickness":"narcolepsy",
"dopebenumbing":"narcotic",
"yarn":"narrate",
"telling":"narration",
"tale":"narrative",
"nosely":"nasal",
"sickly":"naseous",
"swimming pool":"natatorium",
"folk":"nation",
"theedish":"national",
"flagwaving":"nationalism",
"homely":"native",
"clay":"natural",
"smoothly":"naturally",
"clay":"nature",
"barelife":"naturism",
"barefolk":"naturists",
"sickness":"nausea",
"sickening":"nauseous",
"guide":"navigate",
"watercraft":"navigation",
"fleet":"navy",
"Newmandale":"neanderthal",
"starcloud":"nebula",
"needful":"necessary",
"need":"necessitate",
"need":"necessity",
"neckband":"necklace",
"dead":"necro",
"gravelore":"necrology",
"witchcraft":"necromancy",
"licheater":"necrophage",
"licheating":"necrophagy",
"honeyor":"nectar",
"gainsay":"negate",
"naysaying":"negative",
"forget":"neglect",
"heedless":"negligent",
"moot":"negotiate",
"brain bark":"neocortex",
"New Stone Eld":"neolithic",
"newstuff":"neon",
"greenhorn":"neophyte",
"unmourner":"nepenthe",
"neve":"nephew",
"mettle":"nerve",
"edgy":"nervousness",
"sinewsweet":"neurose",
"sinew sender":"neurotransmitter",
"unsided":"neutral",
"unsidedness":"neutrality",
"neitherling":"neutrino",
"neitherbit":"neutron",
"tidings":"newspaper",
"kind":"nice",
"Nickelshowboxx":"nickelodeon",
"nook":"niche",
"nift":"niece",
"Mistworld":"niflheim",
"wearning":"nihilism",
"Nithehewer":"Níðhöggr",
"stickstuff":"nitrogen",
"etheldom":"nobility",
"ethel":"noble",
"nightly":"nocturnal",
"nightstound":"nocturnalinstrument",
"nightswey":"nocturne",
"din":"noise",
"loud":"noisy",
"beckoningly":"nominative",
"call":"nominate",
"un":"non",
"notwithstanding":"non obstante",
"beingless":"nonexistent",
"wordless":"nonverbal",
"rubbish":"nonsense",
"midday":"noon through Latin",
"hangknot":"noose",
"rightline":"norm",
"right":"normal",
"yesterlove":"nostalgia",
"yesterloving":"nostalgic",
"bright":"notable",
"slit":"notch",
"log":"note",
"namecouth":"note of famous",
"take heed":"notice",
"nosely bone":"nasal bone",
"infold":"natural logarithm",
"drain of life":"natural selection",
"Nether Newton":"nizhny novgorod",
"willy-nilly":"nolens volens",
"logbookande":"notary public",
"Hell weed":"noxious weed",
"kernelblaster":"nuclear bomb",
"kerneloven":"nuclear reactor",
"kernelweapon":"nuclear weapon",
"greenmonger":"nutritional therapist",
"wholesome worth":"nutritional value",
"took heed":"noticed",
"striking":"noticeable",
"heeding":"noting",
"nameword":"noun",
"feed":"nourish",
"talebook":"novel",
"newness":"novelty",
"Fogmonth":"November",
"newling":"novice",
"wedworthy":"nubile",
"pithmote":"nucleon",
"kernel":"nucleus",
"nugling":"nugget",
"nuglings":"nuggets",
"hindering":"nuisance",
"naught":"null",
"naughten":"nullify",
"mark":"number",
"teller":"numerator",
"rimlore":"numerological",
"many":"numerous",
"carer":"nurse",
"kindergrove":"nursery",
"breed":"nurture",
"feeding":"nutritious",
"win":"oasis",
"hearsome":"obedient",
"hearsomeness":"obedience",
"needle":"obelisk",
"full":"obese",
"heed":"obey",
"becloud":"obfuscate",
"roufrithsoned":"obituary",
"ware":"object",
"gripe":"objection",
"frainworthy":"objectionable",
"goal":"objective",
"openmindedness":"objectivity",
"bind":"obligate",
"must":"obligation",
"bound":"obligatory",
"bound":"obliged",
"willinghearted":"obliging",
"slanting":"oblique",
"aslant":"obliquely",
"forgetfulness":"oblivion",
"clueless":"oblivious",
"shame":"obrium",
"foul":"obscene",
"thester":"obscure",
"cringing":"obsequious",
"awake":"observant",
"follow":"observe",
"witness":"observer",
"grip":"obsess",
"ravenflint":"obsidian",
"outworn":"obsolete",
"foreset":"obstacle",
"headstrong":"obstinate",
"birthhelp":"obstetrics",
"block":"obstruct",
"hindering":"obstruction",
"get":"obtain",
"straightforward":"obvious",
"sheerly":"obviously",
"time":"occasion",
"here and far between":"occasional",
"every now and then":"occasionally",
"western":"occidental",
"busy":"occupied",
"beset":"occupy",
"befall":"occur",
"befalling":"occurrence",
"eyely":"ocular",
"mere":"ocean",
"eightside":"octagon",
"Winterfulth":"october",
"armfish":"octopus",
"song":"ode",
"Weden":"odin ",
"likelihood":"odds",
"smell":"odour",
"winelust":"oenophilia",
"kiteway":"oesophagus",
"claylish":"of course",
"smite":"offend",
"smiteful":"offensive",
"bid":"offer",
"bids":"offers",
"gift":"offering",
"gifts":"offerings",
"ambight":"office",
"beadle":"officer",
"steward":"official",
"hew":"oid",
"slick":"oil",
"salve":"ointment",
"fatty":"oleaginous",
"smell":"olfactory",
"lore":"ology",
"boding":"omen",
"doomy":"ominous",
"leave out":"omit",
"brainlock":"obsessive compulsive disorder",
"skullend":"occipital bone",
"stickinthemud":"old fashioned",
"Old Bond":"old testament",
"almighty":"omnipotent",
"allknowing":"omniscient",
"hearword":"onomatopoeia",
"ramson":"onion",
"singplay":"opera",
"work":"operate",
"medical scything":"operation",
"undertakings":"operations",
"thought":"opinion",
"whitedeer":"opossum",
"witherling":"opponent",
"timely":"opportune",
"opening":"opportunity",
"be against":"oppose",
"withering":"opposite",
"withstander":"opposition",
"downtrodden":"oppressed",
"tread down":"oppress",
"yoke":"oppression",
"sweer swr":"oppressive",
"smoothen":"optimise",
"smoothen":"optimize",
"yaysaying":"optimism",
"yaysayer":"optimist",
"brightsided":"optimistic",
"best":"optimum",
"can be waled":"optional",
"godspeaker":"oracle",
"uttered":"oral",
"eastern apple":"orange",
"rutherwere":"orangutan",
"outswettling":"oratory",
"go around":"orbit",
"killerwhale":"orca",
"nutgrove":"orchard",
"swaygathering":"orchestra",
"ballockwort":"orchid",
"foreset":"ordain",
"bespeak":"order",
"smooth":"orderly",
"hoding":"ordination",
"book":"organ",
"board":"organization",
"board":"organisation",
"tidy up":"organize",
"tidy up":"organise",
"eastern":"oriental",
"akinting":"orientation",
"hole":"orifice",
"root":"origin",
"roots":"origins",
"ere":"original",
"at first":"originally",
"stem":"originate",
"stemmed":"originated",
"bedeck":"ornament",
"setoff":"ornamentation",
"birdlore":"ornithology",
"sunderling":"orphan",
"mainstream":"orthodox",
"lorespell":"orthodoxy",
"rightspelling":"orthography",
"seahawkfish":"osprey",
"earbone":"ossicle",
"bonelore":"osteology",
"bone brittling":"osteoporosis",
"strutter":"ostrich",
"uproar":"outcry",
"outworn":"outdated",
"outsmart":"outmanoeuvre",
"outdo":"outperform",
"eggshape":"oval",
"slip":"overbalance",
"overload":"overcharge",
"overowed":"overdue",
"overplay":"overemphasize",
"overcrowding":"overpopulation",
"forset":"overpower",
"overburden":"overtax",
"eggling":"ovum",
"rust":"oxidize",
"breath of life":"oxygen",
"sharpdull calque":"oxymoron",
"clam":"oyster",
"fodder":"pabulum",
"speed":"pace",
"soother":"pacifier",
"dove":"pacifist",
"wrapping":"package",
"oar":"paddle",
"heathen":"pagan",
"heathendom":"paganism",
"side":"page",
"allay":"pacify",
"smarting":"pain",
"acheful":"painful",
"dye":"paint",
"meting":"painting",
"dyer":"painter",
"twain":"pair",
"nightclothes":"pajamas",
"hall":"palace",
"roof of the mouth":"palate",
"gums bone":"palatine bone",
"wall":"pale",
"ere":"paleo ",
"old writing":"paleography ",
"orstonely":"paleolithic",
"orwightlore":"paleontology",
"crabword":"palindrome",
"stakehedge":"palisade",
"whitewash":"palliate",
"ashen":"pallid",
"folmtree":"palmtree",
"heriworthy":"palmary ",
"throb":"palpitate",
"flyer":"pamphlet",
"healall":"panacea",
"sweet kernel":"pancreas",
"gut bread":"pancreas",
"greater catbear":"panda bear",
"hexkettle":"pandemonium",
"bedbroker":"panderer",
"shield":"panel",
"Alland":"pangaea",
"shaledeer":"pangolin",
"fright":"panic",
"allsight":"panorama",
"Allsea":"panthalassa",
"breeches":"pants",
"undies":"pants under",
"blasterapple":"papaya",
"leaf":"paper",
"sheetmash":"papiermch",
"over":"para",
"likeness":"parable",
"fallward":"parachute",
"forverghost":"paraclete",
"heaven":"paradise",
"heavenly":"paradisiacal",
"sidewrit":"paragraph",
"alongside":"parallel",
"akinside":"parallelogram",
"lameness":"paralyzedysis",
"lover":"paramour",
"great fear":"paranoia",
"mad misgiver":"paranoid",
"witchcraft":"paranormal",
"inputmark":"paranthesis",
"edwording":"paraphrase",
"bloodsucker":"parasite",
"bloodsucking":"parasitism",
"sunshade":"parasol",
"bookfell":"parchment",
"elder":"parent",
"elderhood":"parenting",
"breeches":"parenthesis",
"elders":"parents",
"better than others":"par excellence",
"outcast":"pariah",
"skullwall":"parietal bone",
"bedeshire":"parish",
"ersh":"park",
"witenmoot":"parliament",
"bleefowl":"parrot",
"mean":"parsimonious",
"crispleaf":"parsley",
"split":"part",
"have":"partake",
"some":"partial",
"join in":"participate",
"dealnimhood":"participation",
"join in":"participant",
"dealnimmand":"participle",
"mote":"particle",
"namely":"particularly",
"wall":"partition",
"mate":"partner",
"childbirth":"parturition",
"gathering":"party",
"upstart":"parvenu",
"tholing":"pascal",
"overtake":"pass",
"path":"passage",
"flow of time":"passage of time",
"faregoer":"passenger",
"love":"passion",
"Lithen":"passion christianity",
"idle":"passive",
"Easter":"Passover",
"wayleave":"passport",
"bygone":"past",
"noodle":"pasta",
"grassland":"pasture",
"kneecap":"patella",
"fatherly":"paternal",
"Our Father":"paternoster",
"sugarbakery":"patisserie",
"rueful":"pathetic",
"sadness":"pathos",
"forbearingness":"patience",
"forbearing":"patient",
"homeland":"patria",
"elder":"patriarch",
"fatherwield":"patriarchy",
"highholder":"patrician",
"fatherslaughter":"patricide",
"fathersland":"patrimony",
"homeloving":"patriotic",
"homelove":"patriotism",
"backer":"patron",
"business":"patronage",
"fathername":"patronym",
"cut":"pattern",
"break":"pause",
"lack":"paucity",
"sidewalk":"pavement",
"yield":"pay",
"fee":"payment",
"handheld":"pda",
"handheld":"personal digital assistant",
"afrith":"peace",
"dovish":"peaceful",
"perseapple ancient Greek calque":"peach",
"ring":"peal",
"earthnut":"peanut",
"seahurst":"pearl",
"churl":"peasant",
"bour":"peasant farmer",
"thefting":"peculation",
"freak":"peculiar",
"teacher":"pedagogue",
"footed":"pedal",
"inkhorny":"pedantic",
"footstone":"pedestal",
"walker":"pedestrian",
"childluster":"pedophile",
"walkingwheel":"pedometer",
"childlust":"pedophilia",
"rend":"peel",
"cast":"peep",
"winged horse":"pegasus",
"slighting":"pejorative",
"wanfoot":"pelican",
"unclouded":"pellucid",
"fell":"pelt",
"marker":"pen",
"bote":"penance",
"leaning":"penchant",
"stick":"pencil",
"breach":"penetrate",
"neck of land":"peninsula",
"fiveside":"pentagon",
"Whitsunday":"Pentecost",
"lastbutone":"penultimate",
"pizzle":"penis",
"rueness":"penitence",
"stingy":"penurious",
"folk":"people",
"croudedswineflesh":"pepperoni",
"wit":"perceive",
"hundredths":"percent",
"hundredmeal":"percentage",
"insight":"perception",
"leach":"percolate",
"forelornness":"perdition",
"duck hawk":"peregrine falcon",
"hone":"perfect",
"forsworn":"perfidious",
"awl":"perforate",
"do forth":"perform",
"duft":"perfume",
"halfhearted":"perfunctory",
"freck OE frcen":"peril",
"while":"period time",
"fullstop":"period punctuation",
"dreeze":"perish",
"forswear":"perjure",
"maybe":"perhaps",
"brim":"perimeter",
"bonch":"perineum",
"everlasting":"permanence",
"everlasting":"permanent",
"everfrost":"permafrost",
"leave":"permission",
"greenlight":"permit",
"baleful":"pernicious",
"chilblain":"pernio",
"athwart":"perpendicular",
"ever":"perpetually",
"forevermore":"perpetuity in",
"bewilder":"perplex",
"ail":"persecute",
"witch hunt":"persecution",
"sticktoitivenesss":"perseverance",
"steadfastness":"persistence",
"steadfast":"persistent",
"someone":"person",
"selfly":"personal",
"selfhood":"personality",
"staff":"personnel",
"outlook":"perspective",
"insightful":"perspicacious",
"insightfulness":"perspicacity",
"bring":"persuade",
"follow":"pursue",
"headstrong":"pertinacious",
"look through":"peruse",
"wade archaic":"pervade",
"overthwart":"perverse",
"twist":"pervert",
"quild":"pestilence",
"send writ":"petition",
"nickname":"pet name",
"stun":"petrify",
"black goldfuel leaded":"petroleum",
"underkirtle":"petticoat",
"sour":"petulant",
"naysaying":"pessimism",
"downbeat":"pessimistic",
"childish":"peurile",
"dream":"phantasm",
"ghost":"phantom",
"speerlining":"phalanx",
"king of Egypt":"pharaoh",
"faker":"pharisee",
"healmiddle":"pharmaceutical",
"druggist":"pharmacist",
"medicinal chemistry":"pharmacy",
"retch":"pharynx",
"wildhen":"pheasant",
"outstanding":"phenomenal",
"happening":"phenomenon",
"lust":"philia",
"Philipsland":"philippines",
"uncouth":"philistine",
"speechwritlorish":"philological",
"speechwritlore":"philology ",
"wisdom":"philosophy",
"throttling":"phimosis",
"bloodletting":"phlebotomy",
"wortrowel":"phloem tube",
"fear":"phobia",
"fearful":"phobic",
"firefowl":"phoenix",
"farspeaker":"phone",
"dinly":"phonetic",
"loudlorish":"phonological",
"reardwork":"phonology",
"lightshedding":"phosphorescent",
"glowstuff":"phosphorus",
"shot":"photograph",
"lightshooting":"photography",
"lightmote":"photon",
"grammar bound":"phrasal",
"wordstring":"phrase",
"stem":"phylum",
"worldken":"physics",
"bodily":"physical",
"leech":"physician",
"beatharp":"pianoforte",
"pike":"pickax",
"likeness":"picture",
"fair":"picturesque",
"bake":"pie",
"bit":"piece",
"little by little":"piecemeal",
"landing":"pier",
"bore":"pierce",
"dove":"pigeon",
"heap":"pile",
"sack":"pillage",
"beadfaring":"pilgrimage",
"mast":"pillar",
"lodeman":"pilot",
"grindwhale":"pilot whale",
"bedbroker":"pimp",
"wheal":"pimple",
"wonderbag":"piata",
"mashed firapple":"pia colada",
"nip":"pinch",
"fir":"pine",
"firapple":"pineapple",
"firtap":"pinecone",
"groundbreaker":"pioneer",
"groundbreaking":"pioneering",
"godly":"pious",
"seed":"pip",
"leat":"pipe",
"seareaver":"pirate",
"highseareaver":"pirate captain",
"peabone":"pisiform bone",
"gun":"pistol",
"sucker":"piston",
"shame":"pity",
"key":"pivotal",
"dot":"pixel",
"flatcake":"pizza",
"spot":"place",
"sunderstow":"place special",
"afterbirth":"placenta",
"thoughttheft":"plagiarism",
"thoughtthief":"plagiarist",
"outbreak":"plague",
"layout":"plan",
"board":"plank",
"drifter moss":"plankton",
"frame":"planning",
"wanderstar":"planet",
"sow":"plant",
"besowen":"planted",
"farmstead":"plantation",
"stirloft":"plasma",
"stickum":"plaster",
"newclay":"plastic",
"dish":"plateau",
"dish":"plate",
"clout":"plate of metal",
"deck":"platform",
"white gold":"platinum",
"hackneyed saying":"platitude",
"watermole":"platypus",
"blessed":"pleasant",
"gladden":"please",
"blissful":"pleased",
"grateful":"pleasing",
"lust":"pleasure",
"folkfrain":"plebiscite",
"pick":"plectrum",
"plight":"pledge",
"rife":"plentiful",
"enoughenow":"plenty",
"overflow":"plethora",
"fold":"plex",
"lithy":"pliable",
"lithy":"pliant",
"feathers":"plumage",
"leatfitter":"plumber",
"leadwork":"plumbing",
"wallthread":"plumbline",
"stroud":"plunder",
"dip":"plunge",
"morefold":"plural",
"and":"plus",
"gelddom":"plutocracy",
"rainly":"pluvial",
"shapely":"pneumatic",
"flintstuffdustsickness":"pneumonoultramicroscopicsilicovolcanoconiosis",
"bag":"pocket",
"lay":"poem",
"scop":"poet",
"leethly":"poetic",
"dighting":"poetry",
"token":"point",
"sakeless":"pointless",
"bane":"poison",
"attery":"poisonous",
"axled":"polar",
"ice bear":"polar bear",
"land of the midnight Sun":"polar zone",
"worldshot":"pole",
"thummart":"polecat",
"rant":"polemic",
"law":"police",
"thew":"policy",
"becoming":"polite",
"mootishparty mootband":"political",
"eggshell speech":"politically correct language",
"lawmaker":"politician",
"shirecraft":"politics",
"survey worthdeem":"poll",
"bloomdust":"pollen",
"foul":"pollute",
"sootdew":"pollution",
"dinghost":"poltergeist",
"manyheadedness":"polycephaly",
"maniwed":"polygamist",
"tonguesmith":"polyglot",
"manihern":"polygon",
"manineb":"polyhedron",
"manishape":"polymorph",
"manishapedom":"polymorphism",
"sundertroth":"polytheism",
"cornapple":"pomegranate",
"showy":"pompous",
"wonder":"ponder",
"twenty one":"pontoon",
"horseling":"pony",
"pot":"pool money",
"needy":"poor",
"folk":"pop",
"Holy Father":"pope",
"folksy":"popular",
"allthedelove":"popularity",
"befolk":"populate",
"folks":"population",
"crowding":"population density",
"folks":"populism",
"folksy":"populist",
"crowded":"populous",
"folkforsaming":"populus assembly",
"shiny earthenware":"porcelain",
"forehouse":"porch",
"pig":"porcine",
"quillpig":"porcupine",
"hole":"pore",
"pigflesh":"pork",
"whoreshowing":"pornography",
"holey":"porous",
"mereswine":"porpoise",
"mush":"porridge",
"harbour":"port",
"handheld":"portable",
"wordmingleword":"portmanteau",
"doorway":"portal",
"bode":"portend",
"foretoken":"portent",
"doomy":"portentous",
"deal":"portion",
"likeness of":"portrait",
"berth":"position",
"upside":"positive aspect",
"mathematics overnaught":"positive",
"own":"possess",
"devilsick":"possessed",
"ownership":"possession",
"likelihood":"possibility",
"likely":"possible",
"maybe":"possibly",
"after":"post",
"rump":"posterior",
"afterness":"posteriority",
"children":"posterity",
"afterlife":"postexistence",
"afterwere":"posthuman",
"afterweredom":"posthumanism",
"forestall":"postpone",
"afterthought":"post script ps",
"potash potash":"potassium",
"earthapple":"potato",
"strength":"potential",
"volt knob":"potentiometer",
"tiverdrink":"potion",
"bag":"pouch",
"fowl":"poultry",
"teem":"pour",
"need":"poverty",
"dust":"powder",
"drive":"power",
"mains line":"power line",
"heavy":"powerful",
"mains brick":"power supply",
"working":"practical",
"about":"practically",
"n oving":"practice ",
"hardheaded":"pragmatic",
"hery":"praise",
"buggy":"pram",
"bead":"prayer",
"beadful":"prayerful",
"fore":"pre",
"athelbid":"preach",
"athelbode":"preacher",
"foreword":"preamble",
"forecare":"precaution",
"herald":"precede",
"beforetime":"preceding",
"walkway":"precinct",
"rainfall":"precipitation",
"dear":"precious",
"dearworthiness":"preciousness",
"spotright":"precise",
"well":"precisely",
"forestall":"preclude",
"ahead":"precocious",
"foreknowledge":"precognition",
"forerunner":"precursor",
"hunter":"predator",
"forerunner":"predecessor",
"wyrdweird":"predestination",
"foredoom":"predetermine",
"swamp":"predicament",
"foretell":"predict",
"foretelling":"prediction",
"overweighing":"predominant",
"foremost":"preeminent",
"aforeness":"preexistence",
"readymade":"prefabricated",
"foreword":"preface",
"fyrdenhighshireman":"prefect",
"forechoose":"prefer",
"liever":"preferable",
"forechoice":"preference",
"foreshadow":"prefigure",
"forefastening":"prefix",
"with child":"pregnant",
"yesteryorely":"prehistoric",
"yesteryorestudy":"prehistory",
"foredeeming":"prejudiceal",
"foredeem":"prejudge",
"foreword":"prelude",
"untimely":"premature",
"beforehand":"prematurely",
"forethought":"premeditated",
"foremost":"premier",
"given":"premise",
"forefeeling":"premonition",
"forebusy":"preoccupy",
"gearing up":"preparation",
"taw":"prepare",
"ready":"prepared",
"alreadiness":"prepreparedness",
"foreput":"preposition",
"forefollow":"prequel",
"foreneed":"prerequisite ",
"sundergift":"prerogative ",
"foreknowledge":"prescience",
"foreknowing":"prescient",
"lay down":"prescribe",
"sight":"presence",
"show":"present",
"Candlemas":"oresentation of the lord",
"forefeeling":"presentiment",
"forlast":"preserve",
"steward":"preside",
"foresitter":"president",
"foresittership":"presidency",
"nighseen":"presque vu",
"thring":"press",
"bethrutch":"press down",
"thringmight":"pressure",
"standing":"prestige",
"foreguess":"presume",
"likely":"presumably",
"uppity":"presumptuous",
"forettle":"presuppose",
"do as if":"pretend",
"did as if":"pretended",
"wouldbe":"pretender",
"backfriend":"pretend friend",
"puton":"pretense",
"showy":"pretentious",
"hold up":"prevail",
"rife":"prevalent",
"hinder":"prevent",
"forelook":"preview",
"former":"previous",
"afore":"previously",
"feng":"prey",
"outlay":"price",
"orgul":"pride",
"leading lady":"prima donna",
"foremostness":"primacy",
"foremost":"primary",
"main":"prime",
"starter":"primer",
"hoary":"primeval",
"frim":"prince",
"highness":"princess",
"frimdom":"principality",
"main":"principle",
"thutch":"print",
"thrycker":"printing press",
"beforehand":"prior",
"rightofway":"priority",
"block":"prism",
"clink":"prison",
"inmate":"prisoner",
"earliest":"pristine",
"hidden":"private",
"right":"privilege",
"gifted":"privileged",
"outhouse":"privy",
"craftsman":"pro",
"likelihood":"probability",
"likely":"probable",
"likely":"probably",
"prod":"probe",
"uprightness":"probity",
"worry":"problem",
"worrysome":"problematic",
"forsetting":"procedure",
"go forward":"proceed",
"foregoes":"proceeds",
"foregoing":"proceeding",
"foregang":"process",
"mainframe":"processor",
"forelike":"proclivity",
"ebb out":"procrastinate",
"ebber":"procrastinator",
"beget":"procreate",
"highshireman":"procurator",
"beshape":"procure",
"ware":"product",
"wonderchild":"prodigy",
"spareless":"prodigal",
"handiwork":"produce",
"begetting":"producing",
"yield":"production",
"waresome":"productive",
"output":"productivity",
"foreword":"proem",
"curse":"profanity",
"worker":"professional",
"lorespeaker":"professor",
"gain":"profit",
"worthwhile":"profitable",
"skill":"proficiency",
"underlying":"profound",
"underlyingly":"profoundly",
"flow thickly":"profusely",
"beteeming":"profusion",
"begetter":"progenitor",
"foredraught":"program",
"inroads":"progress",
"forward":"progressive",
"forbid":"prohibit",
"undertaking":"project",
"beamer":"projector",
"forenut":"prokaryote",
"churls":"proletariat",
"fat":"prolific",
"foretale":"prologue",
"lengthened":"prolonged",
"bedhopping":"promiscuous",
"behight":"promise",
"headland":"promontary",
"uprear":"promote",
"given":"prone",
"tinedeer":"pronghorn antelope",
"byname":"pronoun",
"say":"pronounce",
"wordway":"pronunciation",
"witness":"proof",
"thrust":"propel",
"fitting":"proper",
"selfname":"proper noun",
"ownings":"property",
"foresight":"prophesy",
"foresaw":"prophesied",
"foreseeing":"prophesying",
"seer":"prophet",
"winsome":"propitous",
"foreset":"proposal",
"foreset":"propose",
"householder":"propritor",
"thrust":"propulsion",
"forbid":"proscribe",
"forfollow":"prosecute",
"forfollowing":"prosecution",
"freshman":"proselyte",
"neb blindness":"prosopagnosia",
"thrive":"prosper",
"theedom":"prosperity",
"frim":"prosperous",
"hooker":"prostitute",
"aground":"prostrate",
"lay aground before":"prostrate oneself",
"headfellow":"protagonist",
"foreorfowl":"protarchopteryx",
"ward":"protect",
"shield":"protection",
"mundly":"protective",
"warden":"protector",
"ward":"protg",
"eggwhite":"protein",
"witness":"protest",
"witnessing":"protestantism",
"witness":"protestant",
"ere":"proto",
"eretheedish":"proto-germanic",
"erebit":"proton",
"ereslime":"protoplasm",
"stick out":"protrude",
"knob":"protuberance",
"haughty":"proud",
"show":"prove",
"byword":"proverb",
"afford":"provide",
"landshare":"province",
"gremer":"provocateur",
"greming":"provocation",
"foreship":"prow",
"forewit":"prudence",
"forewitting":"prudent",
"plum":"prune",
"shredding":"pruning",
"blackthorn":"prunus Spinosa",
"Pruceland":"prussia",
"keyhole":"pry",
"keyholing":"prying",
"fake":"pseudo",
"soulkithing":"psychedelic",
"shrink":"psychiatrist",
"soulkith":"psychiatry",
"soulish":"psychic",
"shrink":"psychologist",
"mindlore":"psychology",
"mindsick":"psychopath",
"mindwending":"psychotropic",
"mindwending":"psychoactive",
"shamebone":"pubic bone",
"inn":"public house",
"open":"public",
"theen":"public servant",
"outhouse":"public toilet",
"uttering":"publication",
"utter":"publish",
"utterer":"publisher",
"beat":"pulsate",
"beat":"pulse",
"foamstone":"pumice",
"marrow":"pumpkin",
"pound":"pummel",
"clout":"punch",
"tokenmark":"punctuation",
"wreak":"punish",
"wreak":"punishment",
"whelp":"pup",
"strale":"pupil",
"cat's paw":"puppet",
"buy":"purchase",
"clean":"pure",
"thoroughbred":"purebred",
"Sweepfire":"purgatory",
"cleanse":"purge",
"cleanse":"purify",
"bawse":"purple",
"welktallow":"purple dye",
"bawseswallow":"purple martin",
"sake":"purpose",
"following":"pursuit",
"monger":"purveyor",
"atter":"pus",
"shove":"push",
"weakminded":"pusillanimous",
"pock":"pustule",
"rotting":"putrefaction",
"brainteaser":"puzzle",
"dwarf":"pygmy",
"fourflat":"pyramid",
"firemadness":"pyromania",
"kindler":"pyromaniac",
"fireawe":"pyrophobia",
"yearfour":"quadrennium",
"fourhook":"quadrilateral",
"fourfooted":"quadrupedal",
"fourfold":"quadruple",
"fourfoldling":"quadruplet",
"woodhen":"quail",
"orskill":"qualification",
"fit":"qualify",
"standing":"quality",
"standings":"qualities",
"yelm":"quantity",
"yelms":"quantities",
"selfsunderhood":"quarantine",
"stonepit":"quarry",
"fourth":"quarter",
"almost":"quasi",
"wharf":"quay",
"fare":"quest",
"fares":"quests",
"frain":"question",
"frains":"questions",
"frainful":"questionable",
"row":"queue",
"misunderstanding":"qui pro quo",
"backandforth":"quid pro quo",
"hushed":"quiet",
"lull":"quieten",
"stillness":"quietness",
"stillness":"quietude",
"codapple":"quince",
"swotelsome":"quintessential",
"yearfive":"quinquennium",
"step down":"quit",
"altogether":"quite",
"cocker":"quiver",
"guessing game":"quiz",
"guessing games":"quizes",
"markspeak":"quote",
"markspeaks":"quotes",
"daily":"quotidian"
  
  
  };
    const changes = Object.entries(default_changes);
// NOTE: 'default_changes' must be defined globally or imported elsewhere for this code to run.

function buildRegexBatch(entries) {
    return new RegExp(
        "\\b(" + entries.map(([key]) =>
            key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
        ).join("|") + ")\\b",
        "gi"
    );
}

// The main logic is now inside an async function to be called on DOMContentLoaded
async function performReplacementOnSelection() {
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });

    if (tab) {
        try {
            // 1. Get the selected text from the active tab
            const [{ result: selectedText }] = await chrome.scripting.executeScript({
                target: { tabId: tab.id },
                function: () => window.getSelection().toString(),
            });

            // Check if text was actually selected
            if (!selectedText) {
                document.getElementById('selectedTextDisplay').textContent = 'No text was selected.';
                document.getElementById('trasn').textContent = 'N/A';
                console.log('No text selected.');
                return; // Stop here if nothing is selected
            }
            
            console.log('Selected Text:', selectedText);
            
            let replacedText = selectedText; // Start replacement process with the selected text

            // 2. Perform batched replacement
            for (let i = 0; i < changes.length; i += 500) { // batches of 500 keys
                const batch = changes.slice(i, i + 500);
                const regex = buildRegexBatch(batch);
                
                // Use the string.replace result to update replacedText
                replacedText = replacedText.replace(regex, match => {
                    // Find the replacement value, case-insensitively
                    const replacementEntry = batch.find(([key]) => key.toLowerCase() === match.toLowerCase());
                    
                    if (replacementEntry) {
                        const rep = replacementEntry[1];
                        // Preserve the case of the first letter if the match was capitalized
                        return match[0] === match[0].toUpperCase()
                            ? rep.charAt(0).toUpperCase() + rep.slice(1)
                            : rep;
                    }
                    return match; // Return the original match if no replacement is found (shouldn't happen with the regex setup, but good practice)
                });
            }

            // 3. Display the results
            // Display the original selected text
            document.getElementById('selectedTextDisplay').textContent = ""; 
            // Display the result of the replacement
            document.getElementById('trasn').textContent = replacedText; 

        } catch (e) {
            console.error('Error getting selected text or running script:', e);
            document.getElementById('selectedTextDisplay').textContent = 'Could not get selection on this page (e.g., chrome:// extensions or error).';
            document.getElementById('trasn').textContent = 'Error';
        }
    }
}

// Execute the main function once the popup/document is fully loaded
document.addEventListener('DOMContentLoaded', () => {
    performReplacementOnSelection();
});